import {
  AccountBookOutlined,
  AuditOutlined,
  BarChartOutlined,
  CalendarOutlined,
  DeploymentUnitOutlined,
  DiffOutlined,
  DollarOutlined,
  FallOutlined,
  FieldNumberOutlined,
  FundProjectionScreenOutlined,
  IdcardOutlined,
  MonitorOutlined,
  PercentageOutlined,
  PoweroffOutlined,
  RadarChartOutlined,
  ScheduleOutlined,
  StopOutlined,
  SwapOutlined,
  SyncOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  TransactionOutlined,
  TrophyOutlined,
  UserAddOutlined,
  WalletOutlined,
  WarningOutlined,
  WifiOutlined,
} from "@ant-design/icons";

const variants = {
  teal: {
    accent:
      "linear-gradient(135deg, rgba(14, 165, 233, 0.18), rgba(34, 197, 94, 0.18))",
    iconColor: "#0f766e",
  },
  blue: {
    accent:
      "linear-gradient(135deg, rgba(14, 165, 233, 0.18), rgba(59, 130, 246, 0.28))",
    iconColor: "#0369a1",
  },
  green: {
    accent:
      "linear-gradient(135deg, rgba(74, 222, 128, 0.2), rgba(16, 185, 129, 0.24))",
    iconColor: "#047857",
  },
  indigo: {
    accent:
      "linear-gradient(135deg, rgba(99, 102, 241, 0.16), rgba(14, 165, 233, 0.2))",
    iconColor: "#4338ca",
  },
  amber: {
    accent:
      "linear-gradient(135deg, rgba(34, 197, 94, 0.16), rgba(245, 158, 11, 0.2))",
    iconColor: "#15803d",
  },
  purple: {
    accent:
      "linear-gradient(135deg, rgba(168, 85, 247, 0.14), rgba(59, 130, 246, 0.2))",
    iconColor: "#6d28d9",
  },
  pink: {
    accent:
      "linear-gradient(135deg, rgba(236, 72, 153, 0.14), rgba(59, 130, 246, 0.2))",
    iconColor: "#be185d",
  },
  red: {
    accent:
      "linear-gradient(135deg, rgba(248, 113, 113, 0.18), rgba(245, 158, 11, 0.2))",
    iconColor: "#b91c1c",
  },
  cyan: {
    accent:
      "linear-gradient(135deg, rgba(14, 165, 233, 0.16), rgba(20, 184, 166, 0.2))",
    iconColor: "#0e7490",
  },
};

const createFeatureMenu = ({
  key,
  label,
  description,
  icon,
  loader,
  variant = "teal",
  tabLabel = label,
}) => ({
  key,
  label,
  tabLabel,
  description,
  icon,
  loader,
  ...variants[variant],
});

export const featureMenus = [
  createFeatureMenu({
    key: "getemulsion",
    label: "Cek Emulsion Pelanggan",
    description: "Pengecekan data Emulsion dari AP2T dan New AP2T.",
    icon: BarChartOutlined,
    loader: () => import("../../modules/getemulsion/pages/GetEmulsionPage"),
    variant: "yellow",
  }),
  createFeatureMenu({
    key: "cekbeban",
    label: "Cek Perhitungan Beban",
    description: "Validasi data pelanggan beban dari AP2T dan New AP2T.",
    icon: BarChartOutlined,
    loader: () => import("../../modules/cekbeban/pages/CekBebanPage"),
    variant: "blue",
  }),
  createFeatureMenu({
    key: "cekreduksirp0",
    label: "Cek Reduksi Habis Pasca",
    description: "Pantau reduksi habis pasca yang muncul kembali berdasarkan bulan rekening.",
    icon: FallOutlined,
    loader: () => import("../../modules/cekreduksirp0/pages/cekReduksiRp0Page"),
    variant: "red",
  }),
  createFeatureMenu({
    key: "cekreduksistimulus",
    label: "Cek Reduksi Stimulus",
    description: "Pantau reduksi stimulus yang muncul kembali berdasarkan bulan rekening.",
    icon: SyncOutlined,
    loader: () => import("../../modules/cekreduksistimulus/pages/pages/CekReduksiStimulusPage"),
    variant: "red",
  }),
  createFeatureMenu({
    key: "ceksaldoreduksi",
    label: "Cek Saldo BDT",
    description: "Saldo BDT Bulan lalu tidak sama bulan ini",
    icon: WalletOutlined,
    loader: () => import("../../modules/ceksaldoreduksi/pages/CekSaldoReduksiPage"),
    variant: "red",
  }),
  createFeatureMenu({
    key: "ceksaldostimulus",
    label: "Cek Saldo Stimulus",
    description: "Mengecek saldo stimulus berdasarkan bulan rekening dan IDPEL opsional.",
    icon: WalletOutlined,
    loader: () => import("../../modules/ceksaldostimulus/pages/CekSaldoStimulusPage"),
    variant: "blue",
  }),
  createFeatureMenu({
    key: "cekstimulus",
    label: "Cek Selisih Unsur Trans Stimulus",
    description: "Validasi selisih unsur trans stimulus berdasarkan bulan rekening.",
    icon: TransactionOutlined,
    loader: () => import("../../modules/cekstimulus/pages/CekStimulusPage"),
    variant: "purple",
  }),
  createFeatureMenu({
    key: "cekcurah",
    label: "Cek RPTAG 0",
    description: "Pantau data pelanggan dengan RPTAG 0 berdasarkan bulan rekening.",
    icon: StopOutlined,
    loader: () => import("../../modules/cekcurah/pages/CekCurahPage"),
    variant: "indigo",
  }),
  createFeatureMenu({
    key: "cekmaterai",
    label: "Cek Materai",
    description: "Validasi data materai berdasarkan rule nominal dan IDPEL opsional.",
    icon: AuditOutlined,
    loader: () => import("../../modules/cekmaterai/pages/CekMateraiPage"),
  }),
  createFeatureMenu({
    key: "cekjamnyala",
    label: "Cek Dibawah 40 Jam Nyala",
    description: "Monitoring pelanggan dengan jam nyala rendah agar cepat terdeteksi.",
    icon: CalendarOutlined,
    loader: () => import("../../modules/cekjamnyala/pages/CekJamNyalaPage"),
    variant: "green",
  }),
  createFeatureMenu({
    key: "cekrppnr3",
    label: "Cek PPN",
    description: "Validasi PPN Tarif R3, Sewa Kapasitor, Sewa Trafo, BP Trafo, dan RP PPN > 0.",
    icon: PercentageOutlined,
    loader: () => import("../../modules/cekrppnr3/pages/CekRpPpnR3Page"),
    variant: "amber",
  }),
  createFeatureMenu({
    key: "cekspel",
    label: "Cek Pelanggan SPEL",
    description: "Validasi pelanggan SPEL berdasarkan bulan rekening, UNITUPI, dan IDPEL dengan KDPT SP",
    icon: IdcardOutlined,
    loader: () => import("../../modules/cekspel/pages/CekSpelPage"),
    variant: "cyan",
  }),
  createFeatureMenu({
    key: "cekplgbts",
    label: "Pengecekan Pelanggan Layanan Prioritas (KDPT LP)",
    description: "Pengecekan pelanggan pelanggan Layanan Prioritas dengan KDPT (LP).",
    icon: WifiOutlined,
    loader: () => import("../../modules/cekplgbts/pages/CekPlgBtsPage"),
    variant: "red",
  }),
 // createFeatureMenu({
   // key: "cekplgbtsmut",
    //label: "Cek Pelanggan Mutasi BTS, TBG, Telkomsel KDPT C dan Interneux KDPT E",
    //description: "Cek pelanggan mutasi BTS, TBG, Telkomsel KDPT C dan Interneux KDPT E.",
    //icon: DeploymentUnitOutlined,
    //loader: () => import("../../modules/cekplgbtsmut/pages/CekPlgBtsMutPage"),
    //variant: "red",
  //}),
  createFeatureMenu({
    key: "cekplgckvarh",
    label: "Cek Pemakaian kVarh Tertinggi Tarif C",
    description: "Pengecekan pelanggan tarif Curah Tegangan Rendah(TR)",
    icon: ThunderboltOutlined,
    loader: () => import("../../modules/cekplgckvarh/pages/CekPlgCKvarhPage"),
    variant: "red",
  }),
  createFeatureMenu({
    key: "cekpbpks",
    label: "Cek Pelanggan Baru PKS",
    description: "Pengecekan pelanggan baru PKS per IDPEL tambahan",
    icon: UserAddOutlined,
    loader: () => import("../../modules/cekpbpks/pages/CekPbPksPage"),
    variant: "red",
  }),
  createFeatureMenu({
    key: "cekhargatertinggipks",
    label: "Cek Entrian Harga PKS",
    description: "Pengecekan entrain Harga pelanggan PKS per IDPEL tertinggi dan terendah dengan kdpt A",
    icon: TrophyOutlined,
    loader: () => import("../../modules/cekhargatertinggipks/pages/CekHargaTertinggiPksPage"),
    variant: "green",
  }),
  createFeatureMenu({
    key: "ceklp",
    label: "Cek Pelanggan Layanan Prioritas",
    description: "Pengecekan data pelanggan layanan prioritas dengan tarif lwbp lebih dan kurang dari 1644.52",
    icon: TeamOutlined,
    loader: () => import("../../modules/cekplglp/pages/CekPlgLpPage"),
  }),
  createFeatureMenu({
    key: "cekanomaliharibaca",
    label: "Cek Anomali Tanggal Baca",
    description: "Pengecekan detail anomali hari baca AP2T berdasarkan bulan rekening.",
    icon: ScheduleOutlined,
    loader: () => import("../../modules/cekanomaliharibaca/pages/CekAnomaliHariBacaPage"),
    variant: "cyan",
  }),
  createFeatureMenu({
    key: "cekstanmundur",
    label: "Cek Anomali Data Migrasi",
    description: "Pengecekan anomali pelanggan stan mundur migrasi pasca ke pra dan pra ke pasca.",
    icon: SwapOutlined,
    loader: () => import("../../modules/cekstanmundur/pages/CekStanMundurPage"),
    variant: "red",
  }),
  createFeatureMenu({
    key: "vwbilling720jn",
    label: "Cek Jam Nyala diatas 720",
    description: "Monitoring data VW Billing 720 JN berdasarkan bulan rekening.",
    icon: AccountBookOutlined,
    loader: () => import("../../modules/vwbilling720jn/pages/VwBilling720JnPage"),
  }),
  createFeatureMenu({
    key: "cekselisihunsurptl",
    label: "Cek Selisih Unsur PTL",
    description: "Validasi selisih unsur PTL berdasarkan bulan rekening, UNITUPI, dan IDPEL.",
    icon: DiffOutlined,
    loader: () => import("../../modules/cekselisihunsurptl/pages/CekSelisihUnsurPtlPage"),
    variant: "pink",
  }),
  createFeatureMenu({
    key: "cekanomalistan",
    label: "Cek Anomali Angka Stan",
    description: "Pengecekan anomali stan pelanggan.",
    icon: RadarChartOutlined,
    loader: () => import("../../modules/cekanomalistan/pages/CekAnomaliStanPage"),
    variant: "cyan",
  }),
  createFeatureMenu({
    key: "cekrpkoma",
    label: "Cek Rupiah Koma",
    description: "Pengecekan koma pada rupiah billing.",
    icon: FieldNumberOutlined,
    loader: () => import("../../modules/cekrpkoma/pages/CekRpKomaPage"),
    variant: "indigo",
  }),
  createFeatureMenu({
    key: "cekanomalipemkwh",
    label: "Cek Selisih Unsur KWH",
    description: "Cek anomali pemakaian kWh pelanggan (pemkwh<>(nvl(kwhlwbp,0)+nvl(kwhwbp,0)+nvl(blok3,0)+nvl(kwh_kompor,0)).",
    icon: FundProjectionScreenOutlined,
    loader: () => import("../../modules/cekanomalipemkwh/pages/CekAnomaliPemkwhPage"),
    variant: "red",
  }),
  createFeatureMenu({
    key: "cekppj",
    label: "Cek PPJ",
    description: "Validasi data PPJ dan beda prosen PPJ berdasarkan bulan rekening.",
    icon: DollarOutlined,
    loader: () => import("../../modules/cekppj/pages/CekPpjPage"),
    variant: "amber",
  }),
  createFeatureMenu({
    key: "cekanomalikelebihankvarh",
    label: "Cek Anomali Stand Akhir kVarh 0g",
    description: "Pengecekan Anomali Stand Akhir kVarh 0 .",
    icon: WarningOutlined,
    loader: () => import("../../modules/cekanomalikelebihankvarh/pages/CekAnomaliKelebihanKvarhPage"),
    variant: "red",
  }),
  createFeatureMenu({
    key: "cekstannomut",
    label: "Cek Stan Mundur AMR/AMI",
    description: "Pengecekan stan mundur pelanggan AMI/AMR atau KDPT A.",
    icon: MonitorOutlined,
    loader: () => import("../../modules/cekstanmundurnomut/pages/CekStanNoMutPage"),
  }),
  createFeatureMenu({
    key: "cekpemwkh0",
    label: "Pengecekan Pemakaian Kwh 0 dan Kelebihan Kvarh",
    description: "Cek pelanggan dengan pemakaian kWh 0 dan kelebihan KVARH.",
    icon: PoweroffOutlined,
    loader: () => import("../../modules/cekpemkh0/pages/CekPemkwh0Page"),
    variant: "red",
  }),
  createFeatureMenu({
    key: "cekanomalijamnyalalwbp",
    label: "Cek Anomali Jamnyala LWBP",
    description: "Pantau anomali jamnyala LWBP berdasarkan bulan rekening.",
    icon: CalendarOutlined,
    loader: () => import("../../modules/cekanomalijamnyalalwbp/pages/CekAnomaliJamnyalaLwbpPage"),
    variant: "cyan",
  }),
  createFeatureMenu({
    key: "Cek Anomali Koreksi Billing",
    label: "Pengecekan Anomali Pelanggan Koreksi Billing",
    description: "Pengecekan Anomali Pelanggan Koreksi Billing.",
    icon: AuditOutlined,
    loader: () => import("../../modules/cekanomalikoreksi/pages/CekAnomaliKoreksiPage"),
    variant: "indigo",
  }),
  createFeatureMenu({
    key: "cekstanpecahtdl",
    label: "Cek Stan Pecah TDL",
    description: "Pengecekan Stan Pecah TDL di AP2T Legacy",
    icon: AccountBookOutlined,
    loader: () => import("../../modules/cekpecahtdl/pages/CekPecahTdlPage"),
    variant: "amber",
  }),
];

export const featureMenuMap = new Map(
  featureMenus.map((featureMenu) => [featureMenu.key, featureMenu]),
);
